#!/usr/bin/env bash
# Bash script that pings an IP address passed as an argument:
# . Accepts a string as an argument
# . Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument passed
# . Ping the IP 5 times

# Check if an IP address argument is provided
if [ $# -eq 0 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

# Extract the IP address from the argument
ip_address=$1

# Perform the ping operation five times
for ((i=1; i<=5; i++)); do
    echo "Ping attempt $i:"
    ping -c 1 "$ip_address"
    echo
done
